import { CongressPerson } from './congressperson';

export enum StateKey {
  AL = 'AL',
  AK = 'AK',
  AZ = 'AZ',
  AR = 'AR',
  CA = 'CA',
  CO = 'CO',
  CT = 'CT',
  DE = 'DE',
  DC = 'DC',
  FL = 'FL',
  GA = 'GA',
  HI = 'HI',
  ID = 'ID',
  IL = 'IL',
  IN = 'IN',
  IA = 'IA',
  KS = 'KS',
  KY = 'KY',
  LA = 'LA',
  ME = 'ME',
  MT = 'MT',
  NE = 'NE',
  NV = 'NV',
  NH = 'NH',
  NJ = 'NJ',
  NM = 'NM',
  NY = 'NY',
  NC = 'NC',
  ND = 'ND',
  OH = 'OH',
  OK = 'OK',
  OR = 'OR',
  MD = 'MD',
  MA = 'MA',
  MI = 'MI',
  MN = 'MN',
  MS = 'MS',
  MO = 'MO',
  PA = 'PA',
  RI = 'RI',
  SC = 'SC',
  SD = 'SD',
  TN = 'TN',
  TX = 'TX',
  UT = 'UT',
  VT = 'VT',
  VA = 'VA',
  WA = 'WA',
  WV = 'WV',
  WI = 'WI',
  WY = 'WY',
  Other = 'Other',
}

export enum StateName {
  Alabama = 'Alabama',
  Alaska = 'Alaska',
  Arizona = 'Arizona',
  Arkansas = 'Arkansas',
  California = 'California',
  Colorado = 'Colorado',
  Connecticut = 'Connecticut',
  Delaware = 'Delaware',
  DistrictOfColumbia = 'District Of Columbia',
  Florida = 'Florida',
  Georgia = 'Georgia',
  Hawaii = 'Hawaii',
  Idaho = 'Idaho',
  Illinois = 'Illinois',
  Indiana = 'Indiana',
  Iowa = 'Iowa',
  Kansas = 'Kansas',
  Kentucky = 'Kentucky',
  Louisiana = 'Louisiana',
  Maine = 'Maine',
  Montana = 'Montana',
  Nebraska = 'Nebraska',
  Nevada = 'Nevada',
  NewHampshire = 'New Hampshire',
  NewJersey = 'New Jersey',
  NewMexico = 'New Mexico',
  NewYork = 'New York',
  NorthCarolina = 'North Carolina',
  NorthDakota = 'North Dakota',
  Ohio = 'Ohio',
  Oklahoma = 'Oklahoma',
  Oregon = 'Oregon',
  Maryland = 'Maryland',
  Massachusetts = 'Massachusetts',
  Michigan = 'Michigan',
  Minnesota = 'Minnesota',
  Mississippi = 'Mississippi',
  Missouri = 'Missouri',
  Pennsylvania = 'Pennsylvania',
  RhodeIsland = 'Rhode Island',
  SouthCarolina = 'South Carolina',
  SouthDakota = 'South Dakota',
  Tennessee = 'Tennessee',
  Texas = 'Texas',
  Utah = 'Utah',
  Vermont = 'Vermont',
  Virginia = 'Virginia',
  Washington = 'Washington',
  WestVirginia = 'West Virginia',
  Wisconsin = 'Wisconsin',
  Wyoming = 'Wyoming',
  Other = 'Other',
}

export const stateNameByStateKey: Record<StateKey, StateName> = {
  [StateKey.AK]: StateName.Alaska,
  [StateKey.AL]: StateName.Alabama,
  [StateKey.AR]: StateName.Arkansas,
  [StateKey.AZ]: StateName.Arizona,
  [StateKey.CA]: StateName.California,
  [StateKey.CO]: StateName.Colorado,
  [StateKey.CT]: StateName.Connecticut,
  [StateKey.DC]: StateName.DistrictOfColumbia,
  [StateKey.DE]: StateName.Delaware,
  [StateKey.FL]: StateName.Florida,
  [StateKey.GA]: StateName.Georgia,
  [StateKey.HI]: StateName.Hawaii,
  [StateKey.IA]: StateName.Iowa,
  [StateKey.ID]: StateName.Idaho,
  [StateKey.IL]: StateName.Illinois,
  [StateKey.IN]: StateName.Indiana,
  [StateKey.KS]: StateName.Kansas,
  [StateKey.KY]: StateName.Kentucky,
  [StateKey.LA]: StateName.Louisiana,
  [StateKey.MA]: StateName.Massachusetts,
  [StateKey.MD]: StateName.Maryland,
  [StateKey.ME]: StateName.Maine,
  [StateKey.MI]: StateName.Michigan,
  [StateKey.MN]: StateName.Minnesota,
  [StateKey.MO]: StateName.Missouri,
  [StateKey.MS]: StateName.Mississippi,
  [StateKey.MT]: StateName.Montana,
  [StateKey.NC]: StateName.NorthCarolina,
  [StateKey.ND]: StateName.NorthDakota,
  [StateKey.NE]: StateName.Nebraska,
  [StateKey.NH]: StateName.NewHampshire,
  [StateKey.NJ]: StateName.NewJersey,
  [StateKey.NM]: StateName.NewMexico,
  [StateKey.NV]: StateName.Nevada,
  [StateKey.NY]: StateName.NewYork,
  [StateKey.OH]: StateName.Ohio,
  [StateKey.OK]: StateName.Oklahoma,
  [StateKey.OR]: StateName.Oregon,
  [StateKey.PA]: StateName.Pennsylvania,
  [StateKey.RI]: StateName.RhodeIsland,
  [StateKey.SC]: StateName.SouthCarolina,
  [StateKey.SD]: StateName.SouthDakota,
  [StateKey.TN]: StateName.Tennessee,
  [StateKey.TX]: StateName.Texas,
  [StateKey.UT]: StateName.Utah,
  [StateKey.VA]: StateName.Virginia,
  [StateKey.VT]: StateName.Vermont,
  [StateKey.WA]: StateName.Washington,
  [StateKey.WI]: StateName.Wisconsin,
  [StateKey.WV]: StateName.WestVirginia,
  [StateKey.WY]: StateName.Wyoming,
  [StateKey.Other]: StateName.Other,
};

export enum TerritoryKey {
  AS = 'AS',
  GU = 'GU',
  MP = 'MP',
  PR = 'PR',
  VI = 'VI',
  Other = 'Other',
}

export enum TerritoryName {
  AmericanSamoa = 'American Samoa',
  Guam = 'Guam',
  NorthernMarianaIslands = 'Northern Mariana Islands',
  PeurtoRico = 'Peurto Rico',
  VirginIslands = 'Virgin Islands',
  Other = 'Other',
}

export const territoryNameByTerritoryKey: Record<
  TerritoryKey,
  TerritoryName
> = {
  [TerritoryKey.AS]: TerritoryName.AmericanSamoa,
  [TerritoryKey.GU]: TerritoryName.Guam,
  [TerritoryKey.MP]: TerritoryName.NorthernMarianaIslands,
  [TerritoryKey.PR]: TerritoryName.PeurtoRico,
  [TerritoryKey.VI]: TerritoryName.VirginIslands,
  [TerritoryKey.Other]: TerritoryName.Other,
};

export const mergedStateNamesByStateKeys = {
  ...stateNameByStateKey,
  ...territoryNameByTerritoryKey,
};

export type StateData = {
  name: StateName | TerritoryName;
  cosponsors: number;
  congressPeople: CongressPerson[];
};
